name: Auto Commit Bot (Every Minute)

on:
  schedule:
    - cron: "/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update TODO file
        run: |
          echo "Last update: $(date)" > TODO.md

      - name: Commit changes
        run: |
          git config user.name "ShivKumar033"
          git config user.email "ShivKumar033@users.noreply.github.com"

          git add TODO.md
          git commit -m " commit $(date)" || echo "No changes"

      - name: Push changes
        run: git push